remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Tester
  - Back-End Developer
  - Software Engineer-Backend
  - Software Developer
  - mongo developer
  - NodeJs Developer
  - Full Stack Developer
  - Web Developer
  - Node.js Developer
  - MERN Stack Developer
  - Front-End Developer
  - Full Stack Engineer
  - React Full Stack Developer
  - Software Engineer-Frontend
  - React UI developer
  - Javascript Developer


locations:
  - USA
  - UK
  - Canada
  - Australia
  - New Zealand
  - European Economic Union Area

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
