remote: false

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - React Developer
  - NodeJS Developer

locations:
  - India

applyOnceAtCompany: false

distance: 100

companyBlacklist:
  - Capgemini
  - Truelancer.com

titleBlacklist:
  - Data Science
  - Data
  - Marketing
  - Sales
  - ServiceNow
  - Python
  - SAP
  - Angular
  - MEAN
  - salesforce
  - Wordpress
  
llm_model_type: openai
llm_model: llama3-8b-8192 
llm_api_url: "https://api.groq.com/openai/v1"

